var annotated_dup =
[
    [ "cb_gen_oneof_param", "structcb__gen__oneof__param.html", null ],
    [ "cb_gen_struct_param", "structcb__gen__struct__param.html", null ],
    [ "cb_reader", "structcb__reader.html", null ],
    [ "check_pair_args", "structcheck__pair__args.html", null ],
    [ "compat_ctx", "structcompat__ctx.html", null ],
    [ "cpp_gen_param", "structcpp__gen__param.html", null ],
    [ "diag_engine", "structdiag__engine.html", null ],
    [ "diag_entry", "structdiag__entry.html", null ],
    [ "do_each_oneof_gen_code_param", "structdo__each__oneof__gen__code__param.html", null ],
    [ "do_each_struct_gen_code_param", "structdo__each__struct__gen__code__param.html", null ],
    [ "enum_container", "structenum__container.html", null ],
    [ "enum_value", "structenum__value.html", null ],
    [ "gen_fields_list_fn_param", "structgen__fields__list__fn__param.html", null ],
    [ "hash_map", "structhash__map.html", null ],
    [ "hash_map_entry", "structhash__map__entry.html", null ],
    [ "include_node", "structinclude__node.html", null ],
    [ "json_context", "structjson__context.html", "structjson__context" ],
    [ "json_field_offset_item", "structjson__field__offset__item.html", null ],
    [ "json_nested_mask", "structjson__nested__mask.html", null ],
    [ "json_parse_param", "structjson__parse__param.html", null ],
    [ "json_pos", "structjson__pos.html", null ],
    [ "marshal_numeric_info", "structmarshal__numeric__info.html", null ],
    [ "mp_gen_oneof_param", "structmp__gen__oneof__param.html", null ],
    [ "mp_gen_struct_param", "structmp__gen__struct__param.html", null ],
    [ "mp_reader", "structmp__reader.html", null ],
    [ "oneof_container", "structoneof__container.html", null ],
    [ "oneof_variant", "structoneof__variant.html", null ],
    [ "options", "structoptions.html", "structoptions" ],
    [ "pos", "structpos.html", null ],
    [ "sstr_s", "structsstr__s.html", null ],
    [ "struct_container", "structstruct__container.html", null ],
    [ "struct_field", "structstruct__field.html", null ],
    [ "struct_parser", "structstruct__parser.html", null ],
    [ "struct_token", "structstruct__token.html", null ],
    [ "validate_ctx", "structvalidate__ctx.html", null ]
];