/**
 * @file json_context.h
 * @brief Thread-safe context structure for JSON parsing
 * 
 * This module provides a thread-safe alternative to global variables for
 * JSON parsing operations. It encapsulates field offset information and
 * hash tables in a context structure protected by a mutex, allowing
 * multiple threads to safely parse JSON concurrently.
 * 
 * Key features:
 * - Thread-safe field lookup using mutex protection
 * - Efficient hash-based field resolution
 * - Support for nested structs and arrays
 * - Zero-copy field offset table management
 */

#ifndef JSON_CONTEXT_H
#define JSON_CONTEXT_H

#include <stdint.h>
#include <pthread.h>

/**
 * @brief Field offset item structure for JSON parsing
 * 
 * Contains metadata about a struct field needed for JSON serialization
 * and deserialization. This includes the field's memory offset within
 * its parent struct, type information, and array status.
 */
struct json_field_offset_item {
    int offset;
    int type_size;
    int field_type;
    const char* field_type_name;
    const char* field_name;
    const char* struct_name;
    int is_array;
};

/**
 * @brief Thread-safe JSON parsing context
 * 
 * Central structure that replaces global variables for JSON parsing.
 * Contains field offset tables and hash structures needed for runtime
 * field resolution during JSON unmarshaling. Protected by a mutex to
 * allow safe concurrent access from multiple threads.
 * 
 * The context does not own the field_offset_items and entry_hash arrays;
 * these typically point to static data generated by the code generator.
 */
struct json_context {
    struct json_field_offset_item *field_offset_items;  /**< Field offset items array */
    int *entry_hash;                                    /**< Hash table for field lookups */
    int entry_hash_size;                               /**< Size of hash table */
    int item_count;                                    /**< Number of field offset items */
    pthread_mutex_t mutex;                             /**< Mutex for thread safety */
};

/**
 * @brief Create a new JSON parsing context
 * 
 * Allocates and initializes a new thread-safe JSON parsing context.
 * The context is created empty and must be initialized with field
 * offset data using json_context_init() before use.
 * 
 * @return Pointer to newly allocated context, or NULL if allocation fails
 * @note Caller must call json_context_free() when done
 * @note The mutex is initialized and ready for use
 */
extern struct json_context* json_context_new(void);

/**
 * @brief Free a JSON parsing context
 * @param ctx Context to free
 */
extern void json_context_free(struct json_context* ctx);

/**
 * @brief Initialize context with field offset data
 * 
 * Configures the context with pointers to field offset arrays and
 * hash tables. These are typically static arrays generated by the
 * code generator. The context does not take ownership of these arrays.
 * 
 * @param ctx Context to initialize (must be non-NULL)
 * @param field_items Array of field offset items (not copied, must remain valid)
 * @param item_count Number of items in field_items array
 * @param hash_table Hash table for fast field lookups (not copied, must remain valid)
 * @param hash_size Size of hash table
 * @return JSON_GEN_SUCCESS on success, JSON_GEN_ERROR_INVALID_PARAM if any pointer is NULL
 * 
 * @note This function is thread-safe
 * @note The arrays must remain valid for the lifetime of the context
 */
extern int json_context_init(struct json_context* ctx,
                     struct json_field_offset_item* field_items,
                     int item_count,
                     int* hash_table,
                     int hash_size);

/**
 * @brief Find field offset item in thread-safe manner
 * 
 * Performs a thread-safe hash-based lookup to find the field offset
 * item for a given struct and field name combination. Uses linear
 * probing for collision resolution.
 * 
 * @param ctx JSON context containing field data
 * @param struct_name Name of the struct containing the field
 * @param field_name Name of the field to find
 * @return Pointer to field offset item if found, or NULL if not found
 * 
 * @note This function is thread-safe (uses mutex)
 * @note Returns NULL if context is not initialized or field doesn't exist
 */
extern struct json_field_offset_item* json_context_find_field(
    struct json_context* ctx,
    const char* struct_name,
    const char* field_name);

#endif /* JSON_CONTEXT_H */
