// Auto-generated Rust module — DO NOT EDIT.
// Generated by json-gen-c with --rust.

#![allow(dead_code, non_snake_case, non_camel_case_types)]

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Color {
    RED,
    GREEN,
    BLUE,
}

#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Status {
    ACTIVE,
    INACTIVE,
    PENDING,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Triangle {
    pub base: f32,
    pub height: f32,
    pub label: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AliasBasic {
    #[serde(rename = "user_name")]
    pub username: String,
    #[serde(rename = "created_at")]
    pub created: i64,
    pub id: i32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreciseInts {
    pub i8: i8,
    pub i16: i16,
    pub i32: i32,
    pub i64: i64,
    pub u8: u8,
    pub u16: u16,
    pub u32: u32,
    pub u64: u64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EdgeCaseStruct {
    pub zero_int: i32,
    pub negative_long: i64,
    pub tiny_float: f32,
    pub huge_double: f64,
    pub false_bool: bool,
    pub empty_string: String,
    pub special_chars_string: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TestStruct {
    pub int_val: i32,
    pub long_val: i64,
    pub float_val: f32,
    pub double_val: f64,
    pub bool_val: bool,
    pub sstr_val: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OptionalOnlyStruct {
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub score: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub active: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub rating: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub precise: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub big_num: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MapIntStruct {
    pub scores: HashMap<String, i32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Circle {
    pub radius: f32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DefaultPrecise {
    #[serde(default = "default_default_precise_i8")]
    pub i8: i8,
    #[serde(default = "default_default_precise_i16")]
    pub i16: i16,
    #[serde(default = "default_default_precise_i32")]
    pub i32: i32,
    #[serde(default = "default_default_precise_u8")]
    pub u8: u8,
    #[serde(default = "default_default_precise_u16")]
    pub u16: u16,
    #[serde(default = "default_default_precise_u32")]
    pub u32: u32,
}

impl Default for DefaultPrecise {
    fn default() -> Self {
        Self {
            i8: -1,
            i16: 256,
            i32: -100000,
            u8: 255,
            u16: 65535,
            u32: 42,
        }
    }
}

#[allow(non_snake_case)]
fn default_default_precise_i8() -> i8 { -1 }

#[allow(non_snake_case)]
fn default_default_precise_i16() -> i16 { 256 }

#[allow(non_snake_case)]
fn default_default_precise_i32() -> i32 { -100000 }

#[allow(non_snake_case)]
fn default_default_precise_u8() -> u8 { 255 }

#[allow(non_snake_case)]
fn default_default_precise_u16() -> u16 { 65535 }

#[allow(non_snake_case)]
fn default_default_precise_u32() -> u32 { 42 }

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DefaultMixed {
    #[serde(rename = "user_count", default = "default_default_mixed_count")]
    pub count: i32,
    pub name: String,
    #[serde(default = "default_default_mixed_enabled")]
    pub enabled: bool,
}

impl Default for DefaultMixed {
    fn default() -> Self {
        Self {
            count: 10,
            name: String::new(),
            enabled: false,
        }
    }
}

#[allow(non_snake_case)]
fn default_default_mixed_count() -> i32 { 10 }

#[allow(non_snake_case)]
fn default_default_mixed_enabled() -> bool { false }

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DefaultBasic {
    #[serde(default = "default_default_basic_count")]
    pub count: i32,
    #[serde(default = "default_default_basic_big")]
    pub big: i64,
    #[serde(default = "default_default_basic_ratio")]
    pub ratio: f32,
    #[serde(default = "default_default_basic_precise")]
    pub precise: f64,
    #[serde(default = "default_default_basic_active")]
    pub active: bool,
    #[serde(default = "default_default_basic_label")]
    pub label: String,
    pub no_default: i32,
}

impl Default for DefaultBasic {
    fn default() -> Self {
        Self {
            count: 42,
            big: 1000000,
            ratio: 3.14_f32,
            precise: 2.718281828_f64,
            active: true,
            label: String::from("hello"),
            no_default: 0,
        }
    }
}

#[allow(non_snake_case)]
fn default_default_basic_count() -> i32 { 42 }

#[allow(non_snake_case)]
fn default_default_basic_big() -> i64 { 1000000 }

#[allow(non_snake_case)]
fn default_default_basic_ratio() -> f32 { 3.14_f32 }

#[allow(non_snake_case)]
fn default_default_basic_precise() -> f64 { 2.718281828_f64 }

#[allow(non_snake_case)]
fn default_default_basic_active() -> bool { true }

#[allow(non_snake_case)]
fn default_default_basic_label() -> String { String::from("hello") }

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AliasOptional {
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    #[serde(rename = "age_years", default)]
    pub age: Option<i32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AliasMixed {
    #[serde(rename = "first_name")]
    pub first: String,
    pub last: String,
    #[serde(rename = "is_active")]
    pub active: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NullableOnlyStruct {
    pub id: i32,
    pub name: Option<String>,
    pub score: Option<i32>,
    pub active: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NestedStruct {
    pub id: i32,
    pub name: String,
    pub embedded: TestStruct,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreciseIntArrays {
    pub i8_arr: [i8; 4],
    pub u32_dyn: Vec<u32>,
    pub i64_dyn: Vec<i64>,
    pub u64_fixed: [u64; 2],
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AliasArray {
    #[serde(rename = "tag_list")]
    pub tags: Vec<String>,
    #[serde(rename = "score_list")]
    pub scores: [i32; 3],
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Rectangle {
    pub width: f32,
    pub height: f32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OptionalFieldsStruct {
    pub required_id: i32,
    pub optional_name: String,
    pub optional_value: f32,
    pub has_data: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreciseIntMap {
    pub i32_map: HashMap<String, i32>,
    pub u64_map: HashMap<String, u64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DefaultEnum {
    #[serde(default = "default_default_enum_color")]
    pub color: Color,
    #[serde(default = "default_default_enum_status")]
    pub status: Status,
}

impl Default for DefaultEnum {
    fn default() -> Self {
        Self {
            color: Color::GREEN,
            status: Status::PENDING,
        }
    }
}

#[allow(non_snake_case)]
fn default_default_enum_color() -> Color { Color::GREEN }

#[allow(non_snake_case)]
fn default_default_enum_status() -> Status { Status::PENDING }

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DefaultNegative {
    #[serde(default = "default_default_negative_neg_int")]
    pub neg_int: i32,
    #[serde(default = "default_default_negative_neg_long")]
    pub neg_long: i64,
    #[serde(default = "default_default_negative_neg_float")]
    pub neg_float: f32,
    #[serde(default = "default_default_negative_neg_double")]
    pub neg_double: f64,
}

impl Default for DefaultNegative {
    fn default() -> Self {
        Self {
            neg_int: -10,
            neg_long: -99999,
            neg_float: -1.5_f32,
            neg_double: -0.001_f64,
        }
    }
}

#[allow(non_snake_case)]
fn default_default_negative_neg_int() -> i32 { -10 }

#[allow(non_snake_case)]
fn default_default_negative_neg_long() -> i64 { -99999 }

#[allow(non_snake_case)]
fn default_default_negative_neg_float() -> f32 { -1.5_f32 }

#[allow(non_snake_case)]
fn default_default_negative_neg_double() -> f64 { -0.001_f64 }

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Person {
    pub name: String,
    pub age: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MapArrayStruct {
    pub tags: Vec<HashMap<String, i32>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EnumTestStruct {
    pub color: Color,
    pub status: Status,
    pub value: i32,
    pub colors: Vec<Color>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct House {
    pub number: String,
    pub street: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OptionalNullableStruct {
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub score: Option<i32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DefaultOptional {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub score: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
}

impl Default for DefaultOptional {
    fn default() -> Self {
        Self {
            score: Some(100),
            name: Some(String::from("anonymous")),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Shape {
    #[serde(rename = "circle")]
    Circle(Circle),
    #[serde(rename = "rectangle")]
    Rectangle(Rectangle),
    #[serde(rename = "triangle")]
    Triangle(Triangle),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ComplexStruct {
    pub simple_int: i32,
    pub simple_long: i64,
    pub simple_float: f32,
    pub simple_double: f64,
    pub simple_bool: bool,
    pub simple_string: String,
    pub int_array: Vec<i32>,
    pub long_array: Vec<i64>,
    pub float_array: Vec<f32>,
    pub double_array: Vec<f64>,
    pub string_array: Vec<String>,
    pub address: House,
    pub contacts: Vec<Person>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MapAllTypesStruct {
    pub int_map: HashMap<String, i32>,
    pub long_map: HashMap<String, i64>,
    pub float_map: HashMap<String, f32>,
    pub double_map: HashMap<String, f64>,
    pub bool_map: HashMap<String, bool>,
    pub str_map: HashMap<String, String>,
    pub enum_map: HashMap<String, Color>,
    pub struct_map: HashMap<String, Person>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FixedArrayStruct {
    pub fixed_ints: [i32; 5],
    pub fixed_longs: [i64; 3],
    pub fixed_floats: [f32; 4],
    pub fixed_doubles: [f64; 3],
    pub fixed_strings: [String; 3],
    pub fixed_bools: [bool; 2],
    pub fixed_colors: [Color; 3],
    pub fixed_contacts: [Person; 2],
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Drawing {
    pub name: String,
    pub shape: Shape,
    pub shapes: Vec<Shape>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AliasNested {
    #[serde(rename = "user_info")]
    pub info: Person,
    #[serde(rename = "home_address")]
    pub addr: House,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Data {
    pub house: House,
    pub people: Vec<Person>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NullableNestedStruct {
    pub id: i32,
    pub person: Option<Person>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub color: Option<Color>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub status: Option<Status>,
}

