/**
 * @file gencode_cpp.c
 * @brief Generate a C++ wrapper header (.gen.hpp) providing RAII classes
 * around the generated C structs, with typed accessors and marshal/unmarshal
 * member functions.
 */

#include "gencode/gencode.h"
#include "struct/struct_parse.h"
#include "utils/hash_map.h"
#include "utils/sstr.h"

#include <stdio.h>
#include <string.h>

/* Wire-format prefixes for marshal/unmarshal function names. */

static const char* unmarshal_prefix_for_format(int format) {
    switch (format) {
        case 1:  return "msgpack_unpack_";
        case 2:  return "cbor_unpack_";
        default: return "json_unmarshal_";
    }
}

static const char* marshal_indent_prefix(int format) {
    switch (format) {
        case 1:  return "msgpack_pack_";
        case 2:  return "cbor_pack_";
        default: return "json_marshal_indent_";
    }
}

/* Return the C++ type string for a getter return type. */
static const char* cpp_getter_type(int field_type) {
    switch (field_type) {
        case FIELD_TYPE_INT:    return "int";
        case FIELD_TYPE_LONG:   return "long";
        case FIELD_TYPE_FLOAT:  return "float";
        case FIELD_TYPE_DOUBLE: return "double";
        case FIELD_TYPE_BOOL:   return "bool";
        case FIELD_TYPE_SSTR:   return "std::string";
        case FIELD_TYPE_INT8:   return "int8_t";
        case FIELD_TYPE_INT16:  return "int16_t";
        case FIELD_TYPE_INT32:  return "int32_t";
        case FIELD_TYPE_INT64:  return "int64_t";
        case FIELD_TYPE_UINT8:  return "uint8_t";
        case FIELD_TYPE_UINT16: return "uint16_t";
        case FIELD_TYPE_UINT32: return "uint32_t";
        case FIELD_TYPE_UINT64: return "uint64_t";
        default:                return NULL;
    }
}

static int is_scalar_type(int field_type) {
    return (field_type >= FIELD_TYPE_INT && field_type <= FIELD_TYPE_DOUBLE)
        || field_type == FIELD_TYPE_BOOL
        || (field_type >= FIELD_TYPE_INT8 && field_type <= FIELD_TYPE_UINT64);
}

/* ========================================================================= */
/* Header / footer                                                           */
/* ========================================================================= */

static void emit_header(sstr_t out, const char* c_header_name) {
    sstr_append_cstr(out,
        "// Auto-generated C++ wrapper header — DO NOT EDIT.\n"
        "// Generated by json-gen-c with --cpp-wrapper.\n"
        "#pragma once\n\n"
        "#include <string>\n"
        "#include <cstring>\n"
        "#include <stdexcept>\n"
        "#include <utility>\n"
        "#include <vector>\n\n");
    sstr_append_cstr(out, "#include \"");
    sstr_append_cstr(out, c_header_name);
    sstr_append_cstr(out, "\"\n\n");
    sstr_append_cstr(out, "namespace jgc {\n\n");
}

static void emit_footer(sstr_t out) {
    sstr_append_cstr(out, "} // namespace jgc\n");
}

/* ========================================================================= */
/* Per-field accessor generation                                             */
/* ========================================================================= */

static void emit_scalar_accessors(sstr_t out, struct struct_field* f,
                                  const char* struct_name) {
    const char* ctype = cpp_getter_type(f->type);
    const char* fname = sstr_cstr(f->name);
    (void)struct_name;

    /* getter */
    sstr_append_cstr(out, "    ");
    sstr_append_cstr(out, ctype);
    sstr_append_cstr(out, " ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() const { return data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "; }\n");

    /* setter */
    sstr_append_cstr(out, "    void set_");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "(");
    sstr_append_cstr(out, ctype);
    sstr_append_cstr(out, " v) { data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, " = v; }\n");
}

static void emit_bool_accessors(sstr_t out, struct struct_field* f,
                                const char* struct_name) {
    const char* fname = sstr_cstr(f->name);
    (void)struct_name;

    /* In C, bool fields may be emitted as int; cast for safety */
    sstr_append_cstr(out, "    bool ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() const { return static_cast<bool>(data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "); }\n");

    sstr_append_cstr(out, "    void set_");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "(bool v) { data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, " = v; }\n");
}

static void emit_string_accessors(sstr_t out, struct struct_field* f) {
    const char* fname = sstr_cstr(f->name);

    /* getter returns std::string; handles NULL sstr_t from _init */
    sstr_append_cstr(out, "    std::string ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() const {\n"
                          "        if (!data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, ") return std::string();\n"
                          "        return std::string(sstr_cstr(data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "), sstr_length(data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "));\n    }\n");

    /* setter from std::string; creates sstr_t if NULL */
    sstr_append_cstr(out, "    void set_");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "(const std::string& v) {\n"
                          "        if (!data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, ") data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, " = sstr_new();\n"
                          "        sstr_clear(data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, ");\n"
                          "        sstr_append_of(data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, ", v.data(), v.size());\n    }\n");

    /* setter from C string; creates sstr_t if NULL */
    sstr_append_cstr(out, "    void set_");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "(const char* v) {\n"
                          "        if (!data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, ") data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, " = sstr_new();\n"
                          "        sstr_clear(data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, ");\n"
                          "        sstr_append_cstr(data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, ", v);\n    }\n");
}

static void emit_enum_accessors(sstr_t out, struct struct_field* f) {
    const char* fname = sstr_cstr(f->name);
    const char* tname = sstr_cstr(f->type_name);

    sstr_append_cstr(out, "    enum ");
    sstr_append_cstr(out, tname);
    sstr_append_cstr(out, " ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() const { return static_cast<enum ");
    sstr_append_cstr(out, tname);
    sstr_append_cstr(out, ">(data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "); }\n");

    sstr_append_cstr(out, "    void set_");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "(enum ");
    sstr_append_cstr(out, tname);
    sstr_append_cstr(out, " v) { data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, " = v; }\n");
}

static void emit_struct_accessors(sstr_t out, struct struct_field* f) {
    const char* fname = sstr_cstr(f->name);
    const char* tname = sstr_cstr(f->type_name);

    /* mutable C struct reference — use :: to escape jgc namespace */
    sstr_append_cstr(out, "    struct ::");
    sstr_append_cstr(out, tname);
    sstr_append_cstr(out, "& ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() { return data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "; }\n");

    /* const C struct reference */
    sstr_append_cstr(out, "    const struct ::");
    sstr_append_cstr(out, tname);
    sstr_append_cstr(out, "& ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() const { return data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "; }\n");
}

/* Return the C pointer type string for array element access.
   In the generated C code, bool and enum are stored as int. */
static const char* c_array_element_type(int field_type, const char* type_name) {
    switch (field_type) {
        case FIELD_TYPE_INT:    return "int*";
        case FIELD_TYPE_LONG:   return "long*";
        case FIELD_TYPE_FLOAT:  return "float*";
        case FIELD_TYPE_DOUBLE: return "double*";
        case FIELD_TYPE_BOOL:   return "int*";   /* C stores bool as int */
        case FIELD_TYPE_ENUM:   return "int*";   /* C stores enum as int */
        case FIELD_TYPE_SSTR:   return "sstr_t*";
        case FIELD_TYPE_INT8:   return "int8_t*";
        case FIELD_TYPE_INT16:  return "int16_t*";
        case FIELD_TYPE_INT32:  return "int32_t*";
        case FIELD_TYPE_INT64:  return "int64_t*";
        case FIELD_TYPE_UINT8:  return "uint8_t*";
        case FIELD_TYPE_UINT16: return "uint16_t*";
        case FIELD_TYPE_UINT32: return "uint32_t*";
        case FIELD_TYPE_UINT64: return "uint64_t*";
        default:                return NULL; /* struct/map handled separately */
    }
    (void)type_name;
}

static void emit_dynamic_array_accessors(sstr_t out, struct struct_field* f) {
    const char* fname = sstr_cstr(f->name);
    const char* ptr_type = c_array_element_type(f->type, sstr_cstr(f->type_name));

    if (ptr_type) {
        sstr_append_cstr(out, "    ");
        sstr_append_cstr(out, ptr_type);
        sstr_append_cstr(out, " ");
    } else if (f->type == FIELD_TYPE_STRUCT) {
        sstr_append_cstr(out, "    struct ::");
        sstr_append_cstr(out, sstr_cstr(f->type_name));
        sstr_append_cstr(out, "* ");
    } else {
        sstr_append_cstr(out, "    void* ");
    }
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "_data() { return data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "; }\n");

    /* .field_len() → length */
    sstr_append_cstr(out, "    int ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "_len() const { return data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "_len; }\n");
}

static void emit_fixed_array_accessors(sstr_t out, struct struct_field* f) {
    const char* fname = sstr_cstr(f->name);
    const char* ptr_type = c_array_element_type(f->type, sstr_cstr(f->type_name));
    char size_str[32];
    snprintf(size_str, sizeof(size_str), "%d", f->array_size);

    /* .field_data() → pointer to first element */
    if (ptr_type) {
        sstr_append_cstr(out, "    ");
        sstr_append_cstr(out, ptr_type);
        sstr_append_cstr(out, " ");
    } else if (f->type == FIELD_TYPE_STRUCT) {
        sstr_append_cstr(out, "    struct ::");
        sstr_append_cstr(out, sstr_cstr(f->type_name));
        sstr_append_cstr(out, "* ");
    } else {
        sstr_append_cstr(out, "    void* ");
    }
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "_data() { return data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "; }\n");

    /* .field_size() → compile-time size */
    sstr_append_cstr(out, "    static constexpr int ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "_size() { return ");
    sstr_append_cstr(out, size_str);
    sstr_append_cstr(out, "; }\n");
}

static void emit_map_accessors(sstr_t out, struct struct_field* f) {
    const char* fname = sstr_cstr(f->name);
    /* Map fields have C struct types like json_map_int, json_map_sstr_t, etc.
       The C struct name depends on the actual storage type, not the schema type.
       bool and enum are stored as int, so their maps use json_map_int. */
    const char* c_map_suffix;
    switch (f->map_value_type) {
        case FIELD_TYPE_INT:    c_map_suffix = "int"; break;
        case FIELD_TYPE_LONG:   c_map_suffix = "long"; break;
        case FIELD_TYPE_FLOAT:  c_map_suffix = "float"; break;
        case FIELD_TYPE_DOUBLE: c_map_suffix = "double"; break;
        case FIELD_TYPE_BOOL:   c_map_suffix = "int"; break;
        case FIELD_TYPE_ENUM:   c_map_suffix = "int"; break;
        case FIELD_TYPE_SSTR:   c_map_suffix = "sstr_t"; break;
        case FIELD_TYPE_INT8:   c_map_suffix = "int8_t"; break;
        case FIELD_TYPE_INT16:  c_map_suffix = "int16_t"; break;
        case FIELD_TYPE_INT32:  c_map_suffix = "int32_t"; break;
        case FIELD_TYPE_INT64:  c_map_suffix = "int64_t"; break;
        case FIELD_TYPE_UINT8:  c_map_suffix = "uint8_t"; break;
        case FIELD_TYPE_UINT16: c_map_suffix = "uint16_t"; break;
        case FIELD_TYPE_UINT32: c_map_suffix = "uint32_t"; break;
        case FIELD_TYPE_UINT64: c_map_suffix = "uint64_t"; break;
        case FIELD_TYPE_STRUCT: c_map_suffix = sstr_cstr(f->map_value_type_name); break;
        default:                c_map_suffix = sstr_cstr(f->map_value_type_name); break;
    }

    sstr_append_cstr(out, "    struct ::json_map_");
    sstr_append_cstr(out, c_map_suffix);
    sstr_append_cstr(out, "& ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() { return data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "; }\n");

    sstr_append_cstr(out, "    const struct ::json_map_");
    sstr_append_cstr(out, c_map_suffix);
    sstr_append_cstr(out, "& ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() const { return data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "; }\n");
}

static void emit_oneof_accessors(sstr_t out, struct struct_field* f) {
    const char* fname = sstr_cstr(f->name);
    const char* tname = sstr_cstr(f->type_name);

    /* .field() → mutable reference — use :: to escape jgc namespace */
    sstr_append_cstr(out, "    struct ::");
    sstr_append_cstr(out, tname);
    sstr_append_cstr(out, "& ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() { return data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "; }\n");

    sstr_append_cstr(out, "    const struct ::");
    sstr_append_cstr(out, tname);
    sstr_append_cstr(out, "& ");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() const { return data_.");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "; }\n");
}

static void emit_optional_helpers(sstr_t out, struct struct_field* f) {
    const char* fname = sstr_cstr(f->name);

    sstr_append_cstr(out, "    bool has_");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() const { return data_.has_");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, " != 0; }\n");

    sstr_append_cstr(out, "    void set_has_");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "(bool v) { data_.has_");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, " = v; }\n");
}

static void emit_nullable_helpers(sstr_t out, struct struct_field* f) {
    const char* fname = sstr_cstr(f->name);

    /* Nullable fields also use has_<field> in the C struct. When the field
       is nullable-only (not optional), has_<field> == false means null. */
    sstr_append_cstr(out, "    bool has_");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, "() const { return data_.has_");
    sstr_append_cstr(out, fname);
    sstr_append_cstr(out, " != 0; }\n");
}

/* Emit all accessors for a single field. */
static void emit_field_accessors(sstr_t out, struct struct_field* f,
                                 const char* struct_name) {
    if (f->is_array && f->array_size > 0) {
        emit_fixed_array_accessors(out, f);
    } else if (f->is_array) {
        emit_dynamic_array_accessors(out, f);
    } else if (f->type == FIELD_TYPE_SSTR) {
        emit_string_accessors(out, f);
    } else if (f->type == FIELD_TYPE_BOOL) {
        emit_bool_accessors(out, f, struct_name);
    } else if (f->type == FIELD_TYPE_ENUM) {
        emit_enum_accessors(out, f);
    } else if (f->type == FIELD_TYPE_STRUCT) {
        emit_struct_accessors(out, f);
    } else if (f->type == FIELD_TYPE_MAP) {
        emit_map_accessors(out, f);
    } else if (f->type == FIELD_TYPE_ONEOF) {
        emit_oneof_accessors(out, f);
    } else if (is_scalar_type(f->type)) {
        emit_scalar_accessors(out, f, struct_name);
    }

    if (f->is_optional) {
        emit_optional_helpers(out, f);
    } else if (f->is_nullable) {
        /* Only emit has_ if not already emitted by optional */
        emit_nullable_helpers(out, f);
    }
}

/* ========================================================================= */
/* Per-struct class generation                                               */
/* ========================================================================= */

struct cpp_gen_param {
    sstr_t output;
    int format;
    struct hash_map* dependency_map;
    struct hash_map* oneof_map;
};

static void gen_cpp_class(struct struct_container* sc, int format, sstr_t out) {
    const char* name = sstr_cstr(sc->name);
    const char* marshal_pfix = marshal_indent_prefix(format);
    const char* unmarshal_pfix = unmarshal_prefix_for_format(format);
    int is_json = (format == 0);

    sstr_append_cstr(out, "class ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, " {\npublic:\n");

    /* Default constructor */
    sstr_append_cstr(out, "    ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "() { ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "_init(&data_); }\n");

    /* Destructor */
    sstr_append_cstr(out, "    ~");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "() { ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "_clear(&data_); }\n\n");

    /* Move constructor */
    sstr_append_cstr(out, "    ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "(");
    sstr_append_cstr(out, name);
    if (is_json) {
        sstr_append_cstr(out, "&& other) noexcept {\n"
                              "        ");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "_init(&data_);\n"
                              "        (void)");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "_move(&data_, &other.data_);\n"
                              "    }\n");
    } else {
        sstr_append_cstr(out, "&& other) noexcept {\n"
                              "        std::memcpy(&data_, &other.data_, sizeof(data_));\n"
                              "        std::memset(&other.data_, 0, sizeof(other.data_));\n"
                              "    }\n");
    }

    /* Move assignment */
    sstr_append_cstr(out, "    ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "& operator=(");
    sstr_append_cstr(out, name);
    if (is_json) {
        sstr_append_cstr(out, "&& other) noexcept {\n"
                              "        if (this != &other) {\n"
                              "            (void)");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "_move(&data_, &other.data_);\n"
                              "        }\n"
                              "        return *this;\n"
                              "    }\n\n");
    } else {
        sstr_append_cstr(out, "&& other) noexcept {\n"
                              "        if (this != &other) {\n"
                              "            ");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "_clear(&data_);\n"
                              "            std::memcpy(&data_, &other.data_, sizeof(data_));\n"
                              "            std::memset(&other.data_, 0, sizeof(other.data_));\n"
                              "        }\n"
                              "        return *this;\n"
                              "    }\n\n");
    }

    /* Copy constructor */
    sstr_append_cstr(out, "    ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "(const ");
    sstr_append_cstr(out, name);
    if (is_json) {
        sstr_append_cstr(out, "& other) {\n"
                              "        ");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "_init(&data_);\n"
                              "        if (");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "_copy(&data_, &other.data_) != 0) {\n"
                              "            throw std::runtime_error(\"copy failed\");\n"
                              "        }\n"
                              "    }\n");
    } else {
        sstr_append_cstr(out, "& other) {\n"
                              "        ");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "_init(&data_);\n"
                              "        sstr_t buf = sstr_new();\n"
                              "        ");
        sstr_append_cstr(out, marshal_pfix);
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "(const_cast<struct ::");
        sstr_append_cstr(out, name);
        if (format == 0) {
            sstr_append_cstr(out, "*>(&other.data_), 0, 0, buf);\n");
        } else {
            sstr_append_cstr(out, "*>(&other.data_), buf);\n");
        }
        sstr_append_cstr(out, "        ");
        sstr_append_cstr(out, unmarshal_pfix);
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "(buf, &data_);\n"
                              "        sstr_free(buf);\n"
                              "    }\n");
    }

    /* Copy assignment */
    sstr_append_cstr(out, "    ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "& operator=(const ");
    sstr_append_cstr(out, name);
    if (is_json) {
        sstr_append_cstr(out, "& other) {\n"
                              "        if (this != &other) {\n"
                              "            if (");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "_copy(&data_, &other.data_) != 0) {\n"
                              "                throw std::runtime_error(\"copy failed\");\n"
                              "            }\n"
                              "        }\n"
                              "        return *this;\n"
                              "    }\n\n");
    } else {
        sstr_append_cstr(out, "& other) {\n"
                              "        if (this != &other) {\n"
                              "            ");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "_clear(&data_);\n"
                              "            ");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "_init(&data_);\n"
                              "            sstr_t buf = sstr_new();\n"
                              "            ");
        sstr_append_cstr(out, marshal_pfix);
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "(const_cast<struct ::");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "*>(&other.data_), buf);\n");
        sstr_append_cstr(out, "            ");
        sstr_append_cstr(out, unmarshal_pfix);
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "(buf, &data_);\n"
                              "            sstr_free(buf);\n"
                              "        }\n"
                              "        return *this;\n"
                              "    }\n\n");
    }

    /* ---- Field accessors ---- */
    sstr_append_cstr(out, "    // Field accessors\n");
    struct struct_field* f = sc->fields;
    while (f) {
        emit_field_accessors(out, f, name);
        f = f->next;
    }
    sstr_append_cstr(out, "\n");

    /* ---- marshal() ---- */
    sstr_append_cstr(out, "    /// Serialize to string.\n"
                          "    std::string marshal() const {\n"
                          "        sstr_t buf = sstr_new();\n"
                          "        ");
    sstr_append_cstr(out, marshal_pfix);
    sstr_append_cstr(out, name);
    if (is_json) {
        sstr_append_cstr(out, "(const_cast<struct ::");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "*>(&data_), 0, 0, buf);\n");
    } else {
        sstr_append_cstr(out, "(const_cast<struct ::");
        sstr_append_cstr(out, name);
        sstr_append_cstr(out, "*>(&data_), buf);\n");
    }
    sstr_append_cstr(out,
        "        std::string result(sstr_cstr(buf), sstr_length(buf));\n"
        "        sstr_free(buf);\n"
        "        return result;\n"
        "    }\n\n");

    /* ---- unmarshal() static factory ---- */
    sstr_append_cstr(out, "    /// Deserialize from string. Throws on error.\n"
                          "    static ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, " unmarshal(const std::string& data) {\n"
                          "        ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, " obj;\n"
                          "        sstr_t in = sstr_of(data.data(), data.size());\n"
                          "        int rc = ");
    sstr_append_cstr(out, unmarshal_pfix);
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "(in, &obj.data_);\n"
                          "        sstr_free(in);\n"
                          "        if (rc != 0) throw std::runtime_error(\"unmarshal failed\");\n"
                          "        return obj;\n"
                          "    }\n\n");

    /* ---- unmarshal_into() ---- */
    sstr_append_cstr(out, "    /// Deserialize into this object. Returns true on success.\n"
                          "    bool unmarshal_into(const std::string& data) {\n"
                          "        sstr_t in = sstr_of(data.data(), data.size());\n"
                          "        int rc = ");
    sstr_append_cstr(out, unmarshal_pfix);
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "(in, &data_);\n"
                          "        sstr_free(in);\n"
                          "        return rc == 0;\n"
                          "    }\n\n");

    /* ---- C interop ---- */
    sstr_append_cstr(out, "    /// Access the underlying C struct.\n"
                          "    struct ::");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "& c_struct() { return data_; }\n"
                          "    const struct ::");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "& c_struct() const { return data_; }\n\n");

    /* ---- Equality via marshal comparison ---- */
    sstr_append_cstr(out, "    bool operator==(const ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "& other) const { return marshal() == other.marshal(); }\n");
    sstr_append_cstr(out, "    bool operator!=(const ");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, "& other) const { return !(*this == other); }\n\n");

    /* private data */
    sstr_append_cstr(out, "private:\n"
                          "    struct ::");
    sstr_append_cstr(out, name);
    sstr_append_cstr(out, " data_;\n"
                          "};\n\n");
}

/* ========================================================================= */
/* Dependency-ordered struct iteration (same pattern as gencode.c)           */
/* ========================================================================= */

static void do_each_cpp_struct(void* key, void* value, void* ptr) {
    sstr_t k = (sstr_t)key;
    struct struct_container* sc = (struct struct_container*)value;
    struct cpp_gen_param* param = (struct cpp_gen_param*)ptr;
    struct hash_map* dep_map = param->dependency_map;

    void* dv = NULL;
    if (hash_map_find(dep_map, k, &dv) == HASH_MAP_OK) return;

    /* Check struct-typed field dependencies */
    struct struct_field* f = sc->fields;
    while (f) {
        if (f->type == FIELD_TYPE_STRUCT) {
            if (hash_map_find(dep_map, f->type_name, &dv) != HASH_MAP_OK)
                return;
        }
        if (f->type == FIELD_TYPE_MAP && f->map_value_type == FIELD_TYPE_STRUCT) {
            if (hash_map_find(dep_map, f->map_value_type_name, &dv) != HASH_MAP_OK)
                return;
        }
        if (f->type == FIELD_TYPE_ONEOF) {
            if (hash_map_find(dep_map, f->type_name, &dv) != HASH_MAP_OK)
                return;
        }
        f = f->next;
    }

    gen_cpp_class(sc, param->format, param->output);
    hash_map_insert(dep_map, sstr_dup(k), NULL);
}

/* Oneofs also need forward-declaration handling: emit after variant structs */
static void do_each_cpp_oneof(void* key, void* value, void* ptr) {
    sstr_t k = (sstr_t)key;
    struct oneof_container* oc = (struct oneof_container*)value;
    struct cpp_gen_param* param = (struct cpp_gen_param*)ptr;
    struct hash_map* dep_map = param->dependency_map;

    void* dv = NULL;
    if (hash_map_find(dep_map, k, &dv) == HASH_MAP_OK) return;

    /* Ensure all variant struct types are emitted first */
    struct oneof_variant* v = oc->variants;
    while (v) {
        if (hash_map_find(dep_map, v->struct_type_name, &dv) != HASH_MAP_OK)
            return;
        v = v->next;
    }

    /* Oneofs don't get their own wrapper class - they use the generated
       C tagged union directly. Just mark as resolved. */
    hash_map_insert(dep_map, sstr_dup(k), NULL);
}

static void cpp_dummy_free(void* ptr) { (void)ptr; }

/* ========================================================================= */
/* Public entry point                                                        */
/* ========================================================================= */

int gencode_cpp_wrapper(struct hash_map* struct_map, struct hash_map* enum_map,
                        struct hash_map* oneof_map, const char* c_header_name,
                        int format, sstr_t output) {
    (void)enum_map; /* enums are directly usable from C, no wrapping needed */

    struct hash_map* dep_map =
        hash_map_new(256, sstr_key_hash, sstr_key_cmp, sstr_key_free,
                     cpp_dummy_free);
    if (dep_map == NULL) return -1;

    emit_header(output, c_header_name);

    struct cpp_gen_param param;
    param.output = output;
    param.format = format;
    param.dependency_map = dep_map;
    param.oneof_map = oneof_map;

    int total = struct_map->size + oneof_map->size;
    for (int i = 0; i < total; ++i) {
        hash_map_for_each(struct_map, do_each_cpp_struct, &param);
        hash_map_for_each(oneof_map, do_each_cpp_oneof, &param);
        if (dep_map->size >= total) break;
    }

    if (dep_map->size < total) {
        hash_map_free(dep_map);
        return -1;
    }

    emit_footer(output);
    hash_map_free(dep_map);
    return 0;
}
