name: build run test

on:
  push:
    branches: [ main, enhance ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: sudo apt install -y libbenchmark-dev libgtest-dev doxygen
    - name: Checkout code
      uses: actions/checkout@v2
    - name: make clean
      run: make clean
    - name: make
      run: make
    - name: make example
      run: make example
    - name: make benchmark
      run: make benchmark
    - name: run example
      run: ./build/example/example
    - name: run benchmark
      run: ./build/benchmark/json_bench
    - name: build and run tests
      run: make test
    - name: run individual tests
      run: |
        cd test
        make run-unit
        make run-enhanced
        make run-empty-array
    - name: generate documentation
      run: make doxygen

