name: build run test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install google bench
      run: sudo apt install libbenchmark-dev
    - name: Checkout code
      uses: actions/checkout@v2
    - name: make
      run: make
    - name: make example
      run: make example
    - name: make benchmark
      run: make benchmark
    - name: run example
      run: ./target/example
    - name: run benchmark
      run: ./target/benchmark/json_bench
    - name: run test
      run: ./target/test/simple_test

